apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: fastapi-second
  ports:
    - protocol: 'TCP'
      port: 80
      targetPort: 8000
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-second-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi-second
      tier: backend
  template:
    metadata:
      labels:
        app: fastapi-second
        tier: backend
    spec:
      containers:
        - name: second-node
          image: derabyte/fastapi-kub
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /
              port: 8000
            periodSeconds: 10
            initialDelaySeconds: 10